import { LineName } from "./types";

export const stations = {
    "Acton Town": ["District", "Piccadilly"],
    "Acton Main Line": ["Elizabeth"],
    "Aldgate": ["Metropolitan", "Circle"],
    "Aldgate East": ["Hammersmith City", "District"],
    "Alperton": ["Piccadilly"],
    "Amersham": ["Metropolitan"],
    "Angel": ["Northern"],
    "Archway": ["Northern"],
    "Arnos Grove": ["Piccadilly"],
    "Arsenal": ["Piccadilly"],
    "Baker Street": ["Metropolitan", "Bakerloo", "Circle", "Jubilee", "Hammersmith City"],
    "Balham": ["Northern"],
    "Bank": ["Waterloo City", "Northern", "Central"],
    "Barbican": ["Metropolitan", "Circle", "Hammersmith City"],
    "Barking": ["District", "Hammersmith City"],
    "Barkingside": ["Central"],
    "Barons Court": ["District", "Piccadilly"],
    "Battersea Power Station": ["Northern"],
    "Bayswater": ["District", "Circle"],
    "Becontree": ["District"],
    "Belsize Park": ["Northern"],
    "Bermondsey": ["Jubilee"],
    "Bethnal Green": ["Central"],
    "Blackfriars": ["District", "Circle"],
    "Blackhorse Road": ["Victoria"],
    "Bond Street": ["Central", "Jubilee", "Elizabeth"],
    "Borough": ["Northern"],
    "Boston Manor": ["Piccadilly"],
    "Bounds Green": ["Piccadilly"],
    "Bow Road": ["District", "Hammersmith City"],
    "Brent Cross": ["Northern"],
    "Brixton": ["Victoria"],
    "Bromley-by-Bow": ["District", "Hammersmith City"],
    "Buckhurst Hill": ["Central"],
    "Burnt Oak": ["Northern"],
    "Caledonian Road": ["Piccadilly"],
    "Camden Town": ["Northern"],
    "Canada Water": ["Jubilee"],
    "Canary Wharf": ["Jubilee", "Elizabeth"],
    "Canning Town": ["Jubilee"],
    "Cannon Street": ["District", "Circle"],
    "Canons Park": ["Jubilee"],
    "Chalfont & Latimer": ["Metropolitan"],
    "Chalk Farm": ["Northern"],
    "Chancery Lane": ["Central"],
    "Charing Cross": ["Bakerloo", "Northern"],
    "Chesham": ["Metropolitan"],
    "Chigwell": ["Central"],
    "Chiswick Park": ["District"],
    "Chorleywood": ["Metropolitan"],
    "Clapham Common": ["Northern"],
    "Clapham North": ["Northern"],
    "Clapham South": ["Northern"],
    "Cockfosters": ["Piccadilly"],
    "Colindale": ["Northern"],
    "Colliers Wood": ["Northern"],
    "Covent Garden": ["Piccadilly"],
    "Croxley": ["Metropolitan"],
    "Custom House": ["Elizabeth"],
    "Dagenham East": ["District"],
    "Dagenham Heathway": ["District"],
    "Debden": ["Central"],
    "Dollis Hill": ["Jubilee"],
    "Ealing Broadway": ["District", "Central", "Elizabeth"],
    "Ealing Common": ["District", "Piccadilly"],
    "Earl's Court": ["District", "Piccadilly"],
    "East Acton": ["Central"],
    "East Finchley": ["Northern"],
    "East Ham": ["District", "Hammersmith City"],
    "East Putney": ["District"],
    "Eastcote": ["Metropolitan", "Piccadilly"],
    "Edgware": ["Northern"],
    "Edgware Road": ["Bakerloo", "Hammersmith City", "District", "Circle"],
    "Elephant & Castle": ["Northern", "Bakerloo"],
    "Elm Park": ["District"],
    "Embankment": ["District", "Bakerloo", "Northern", "Circle"],
    "Epping": ["Central"],
    "Euston": ["Northern", "Victoria"],
    "Euston Square": ["Metropolitan", "Circle", "Hammersmith City"],
    "Fairlop": ["Central"],
    "Farringdon": ["Metropolitan", "Circle", "Hammersmith City", "Elizabeth"],
    "Finchley Central": ["Northern"],
    "Finchley Road": ["Metropolitan", "Jubilee"],
    "Finsbury Park": ["Piccadilly", "Victoria"],
    "Fulham Broadway": ["District"],
    "Gants Hill": ["Central"],
    "Gloucester Road": ["District", "Piccadilly", "Circle"],
    "Golders Green": ["Northern"],
    "Goldhawk Road": ["Hammersmith City", "Circle"],
    "Goodge Street": ["Northern"],
    "Grange Hill": ["Central"],
    "Great Portland Street": ["Metropolitan", "Circle", "Hammersmith City"],
    "Greenford": ["Central"],
    "Green Park": ["Piccadilly", "Victoria", "Jubilee"],
    "Gunnersbury": ["District"],
    "Hainault": ["Central"],
    "Hammersmith": ["District", "Piccadilly", "Hammersmith City", "Circle"],
    "Hampstead": ["Northern"],
    "Hanger Lane": ["Central"],
    "Harlesden": ["Bakerloo"],
    "Harrow & Wealdstone": ["Bakerloo"],
    "Harrow-on-the-Hill": ["Metropolitan"],
    "Hatton Cross": ["Piccadilly"],
    "Heathrow": ["Piccadilly", "Elizabeth"],
    "Hendon Central": ["Northern"],
    "High Barnet": ["Northern"],
    "Highbury & Islington": ["Victoria"],
    "Highgate": ["Northern"],
    "High Street Kensington": ["District", "Circle"],
    "Hillingdon": ["Metropolitan", "Piccadilly"],
    "Holborn": ["Central", "Piccadilly"],
    "Holland Park": ["Central"],
    "Holloway Road": ["Piccadilly"],
    "Hornchurch": ["District"],
    "Hounslow Central": ["Piccadilly"],
    "Hounslow East": ["Piccadilly"],
    "Hounslow West": ["Piccadilly"],
    "Hyde Park Corner": ["Piccadilly"],
    "Ickenham": ["Metropolitan", "Piccadilly"],
    "Kennington": ["Northern"],
    "Kensal Green": ["Bakerloo"],
    "Kensington (Olympia)": ["District"],
    "Kentish Town": ["Northern"],
    "Kenton": ["Bakerloo"],
    "Kew Gardens": ["District"],
    "Kilburn": ["Jubilee"],
    "Kilburn Park": ["Bakerloo"],
    "Kingsbury": ["Jubilee"],
    "King's Cross St Pancras": ["Metropolitan", "Northern", "Piccadilly", "Circle", "Victoria", "Hammersmith City"],
    "Knightsbridge": ["Piccadilly"],
    "Ladbroke Grove": ["Hammersmith City", "Circle"],
    "Lambeth North": ["Bakerloo"],
    "Lancaster Gate": ["Central"],
    "Latimer Road": ["Hammersmith City", "Circle"],
    "Leicester Square": ["Piccadilly", "Northern"],
    "Leyton": ["Central"],
    "Leytonstone": ["Central"],
    "Liverpool Street": ["Metropolitan", "Central", "Circle", "Hammersmith City", "Elizabeth"],
    "London Bridge": ["Northern", "Jubilee"],
    "Loughton": ["Central"],
    "Maida Vale": ["Bakerloo"],
    "Manor House": ["Piccadilly"],
    "Mansion House": ["District", "Circle"],
    "Marble Arch": ["Central"],
    "Marylebone": ["Bakerloo"],
    "Mile End": ["District", "Hammersmith City", "Central"],
    "Mill Hill East": ["Northern"],
    "Monument": ["District", "Circle"],
    "Moorgate": ["Metropolitan", "Northern", "Circle", "Hammersmith City"],
    "Moor Park": ["Metropolitan"],
    "Morden": ["Northern"],
    "Mornington Crescent": ["Northern"],
    "Neasden": ["Jubilee"],
    "Newbury Park": ["Central"],
    "Nine Elms": ["Northern"],
    "North Acton": ["Central"],
    "North Ealing": ["Piccadilly"],
    "North Greenwich": ["Jubilee"],
    "North Harrow": ["Metropolitan"],
    "North Wembley": ["Bakerloo"],
    "Northfields": ["Piccadilly"],
    "Northolt": ["Central"],
    "Northwick Park": ["Metropolitan"],
    "Northwood": ["Metropolitan"],
    "Northwood Hills": ["Metropolitan"],
    "Notting Hill Gate": ["District", "Central", "Circle"],
    "Oakwood": ["Piccadilly"],
    "Old Street": ["Northern"],
    "Osterley": ["Piccadilly"],
    "Oval": ["Northern"],
    "Oxford Circus": ["Central", "Bakerloo", "Victoria"],
    "Paddington": ["District", "Circle", "Bakerloo", "Hammersmith City", "Circle", "Elizabeth"],
    "Park Royal": ["Piccadilly"],
    "Parsons Green": ["District"],
    "Perivale": ["Central"],
    "Piccadilly Circus": ["Bakerloo", "Piccadilly"],
    "Pimlico": ["Victoria"],
    "Pinner": ["Metropolitan"],
    "Plaistow": ["District", "Hammersmith City"],
    "Preston Road": ["Metropolitan"],
    "Putney Bridge": ["District"],
    "Queen's Park": ["Bakerloo"],
    "Queensbury": ["Jubilee"],
    "Queensway": ["Central"],
    "Ravenscourt Park": ["District"],
    "Rayners Lane": ["Metropolitan", "Piccadilly"],
    "Redbridge": ["Central"],
    "Regent's Park": ["Bakerloo"],
    "Richmond": ["District"],
    "Rickmansworth": ["Metropolitan"],
    "Roding Valley": ["Central"],
    "Royal Oak": ["Hammersmith City", "Circle"],
    "Ruislip": ["Metropolitan", "Piccadilly"],
    "Ruislip Gardens": ["Central"],
    "Ruislip Manor": ["Metropolitan", "Piccadilly"],
    "Russell Square": ["Piccadilly"],
    "St James's Park": ["District", "Circle"],
    "St John's Wood": ["Jubilee"],
    "St Paul's": ["Central"],
    "Seven Sisters": ["Victoria"],
    "Shepherd's Bush": ["Central"],
    "Shepherd's Bush Market": ["Hammersmith City", "Circle"],
    "Sloane Square": ["District", "Circle"],
    "Snaresbrook": ["Central"],
    "South Ealing": ["Piccadilly"],
    "South Harrow": ["Piccadilly"],
    "South Kensington": ["District", "Piccadilly", "Circle"],
    "South Kenton": ["Bakerloo"],
    "South Ruislip": ["Central"],
    "South Wimbledon": ["Northern"],
    "South Woodford": ["Central"],
    "Southfields": ["District"],
    "Southgate": ["Piccadilly"],
    "Southwark": ["Jubilee"],
    "Stamford Brook": ["District"],
    "Stanmore": ["Jubilee"],
    "Stepney Green": ["District", "Hammersmith City"],
    "Stockwell": ["Northern", "Victoria"],
    "Stonebridge Park": ["Bakerloo"],
    "Stratford": ["Central", "Jubilee", "Elizabeth"],
    "Sudbury Hill": ["Piccadilly"],
    "Sudbury Town": ["Piccadilly"],
    "Swiss Cottage": ["Jubilee"],
    "Temple": ["District", "Circle"],
    "Theydon Bois": ["Central"],
    "Tooting Bec": ["Northern"],
    "Tooting Broadway": ["Northern"],
    "Tottenham Court Road": ["Central", "Northern", "Elizabeth"],
    "Tottenham Hale": ["Victoria"],
    "Totteridge & Whetstone": ["Northern"],
    "Tower Hill": ["District", "Circle"],
    "Tufnell Park": ["Northern"],
    "Turnham Green": ["District", "Piccadilly"],
    "Turnpike Lane": ["Piccadilly"],
    "Upminster": ["District"],
    "Upminster Bridge": ["District"],
    "Upney": ["District"],
    "Upton Park": ["District", "Hammersmith City"],
    "Uxbridge": ["Metropolitan", "Piccadilly"],
    "Vauxhall": ["Victoria"],
    "Victoria": ["District", "Circle", "Victoria"],
    "Walthamstow Central": ["Victoria"],
    "Wanstead": ["Central"],
    "Warren Street": ["Northern", "Victoria"],
    "Warwick Avenue": ["Bakerloo"],
    "Waterloo": ["Waterloo City", "Bakerloo", "Northern", "Jubilee"],
    "Watford": ["Metropolitan"],
    "Wembley Central": ["Bakerloo"],
    "Wembley Park": ["Metropolitan", "Jubilee"],
    "West Acton": ["Central"],
    "West Brompton": ["District"],
    "West Finchley": ["Northern"],
    "West Ham": ["District", "Hammersmith City", "Jubilee"],
    "West Hampstead": ["Jubilee"],
    "West Harrow": ["Metropolitan"],
    "West Kensington": ["District"],
    "West Ruislip": ["Central"],
    "Westbourne Park": ["Hammersmith City", "Circle"],
    "Westminster": ["District", "Circle", "Jubilee"],
    "White City": ["Central"],
    "Whitechapel": ["District", "Hammersmith City", "Elizabeth"],
    "Willesden Green": ["Jubilee"],
    "Willesden Junction": ["Bakerloo"],
    "Wimbledon": ["District"],
    "Wimbledon Park": ["District"],
    "Wood Green": ["Piccadilly"],
    "Wood Lane": ["Hammersmith City", "Circle"],
    "Woodford": ["Central"],
    "Woodside Park": ["Northern"]
} as const;

export type StationName = keyof typeof stations;

export const Stations = stations as unknown as Record<StationName, LineName[]>;